# Generated by Django 2.0 on 2018-06-04 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesToCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='card_images')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('m_name', models.CharField(max_length=100)),
                ('f_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='imagestocard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.WeddingCard'),
        ),
    ]
