# Generated by Django 2.0 on 2018-06-06 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestocard',
            name='image_comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='card_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='card_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagestocard',
            name='image',
            field=models.ImageField(upload_to='card_image'),
        ),
    ]
