# Generated by Django 2.0 on 2018-06-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20180614_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestocard',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
